name: DX-Safety CAP Ingestor
version: "0.1.5"
slug: dx_safety
description: "CAP 기반 재난 경보 수신/정규화/정책결정/디스패치 애드온"
arch:
  - amd64
  - aarch64
startup: services
init: false

# Ingress UI
ingress: true
ingress_port: 8099
ingress_entry: "/"

# Home Assistant 공유 디렉토리 마운트
map:
  - "share:rw"
  - "ssl:ro"

# Mosquitto 애드온(선택)
services:
  - "mqtt:want"

options:
  remote_mqtt:
    host: "192.168.144.100"
    port: 1883
    topic: "pws/cap/#"
    qos: 1
    security_mode: "none"         # none | tls | mtls
    ca_cert_path: "/ssl/ca.crt"   # tls/mtls에서 사용
    client_cert_path: ""          # mtls에서 사용
    client_key_path: ""           # mtls에서 사용
    username: ""
    password: ""
    keepalive: 30
    clean_session: true
    client_id: ""                 # 비우면 코드가 자동 생성(지속 세션 필요시 지정)
  local_mqtt:
    host: "core-mosquitto"
    port: 1883
    topic_prefix: "dxsafety"
    qos: 1
    retain: true
  homeassistant_api:
    token: ""                     # Supervisor 토큰 사용 시 비워둘 수 있음
    url: "http://homeassistant:8123"
    timeout: 30
  policy:
    default_location: "zone.home"
    lat: 36.123
    lon: 127.234
    radius_km_buffer: 0
    severity_threshold: "moderate"
    night_mode: false
  tts:
    enabled: false
    topic: "dxsafety/tts"
    template: "{headline} - {description}"
  observability:
    http_port: 8099
    metrics_enabled: true
    log_level: "INFO"
  reliability:
    idempotency_ttl_sec: 86400
    reconnect_max_backoff_sec: 120

schema:
  remote_mqtt:
    host: str
    port: port
    topic: str
    qos: int
    security_mode: list(none|tls|mtls)
    ca_cert_path: str?
    client_cert_path: str?
    client_key_path: str?
    username: str?
    password: password?
    keepalive: int
    clean_session: bool
    client_id: str?
  local_mqtt:
    host: str
    port: port
    topic_prefix: str
    qos: int
    retain: bool
  homeassistant_api:
    token: password?
    url: url
    timeout: int
  policy:
    default_location: str
    lat: float?
    lon: float?
    radius_km_buffer: float
    severity_threshold: list(minor|moderate|severe|critical)
    night_mode: bool
  tts:
    enabled: bool
    topic: str
    template: str
  observability:
    http_port: port
    metrics_enabled: bool
    log_level: str
  reliability:
    idempotency_ttl_sec: int
    reconnect_max_backoff_sec: int

