name: DX-Safety CAP 처리기
version: "0.4.5"
slug: dx_safety
description: "CAP 기반 재난 경보 수신/정규화/정책결정/디스패치 애드온"
arch: [amd64, aarch64]
startup: services
boot: auto
init: false
stage: experimental

homeassistant: "2024.6.0"
homeassistant_api: true     # Core API(http://supervisor/core) 접근 허용
hassio_api: false           # Supervisor API 필요 시 true

# Ingress UI -> 내부 FastAPI(/, /health, /metrics) 노출
ingress: true
ingress_port: 8099
ingress_entry: "/"
panel_title: "DX-Safety"
panel_icon: "mdi:shield-alert"

# 헬스 체크(워치독)
watchdog: "http://[HOST]:8099/health"

# 공유 디렉토리
map:
  - "share:rw"
  - "ssl:ro"
  - "config:rw"

# Mosquitto 애드온(선택)
services:
  - "mqtt:need"

options:
  remote_mqtt:
    host: "192.168.144.100"
    port: 1883
    topic: "pws/cap/#"
    qos: 1
    security_mode: "none"          # none | tls | mtls
    ca_cert_path: "/ssl/ca.crt"    # tls/mtls에서 사용
    client_cert_path: ""           # mtls에서 사용
    client_key_path: ""            # mtls에서 사용
    username: ""
    password: ""
    keepalive: 30
    clean_session: true
    client_id: ""
  local_mqtt:
    host: "localhost"              # "localhost"면 런타임에 core-mosquitto로 자동 치환
    port: 1883
    topic_prefix: "dxsafety"
    qos: 1
    retain: true
    enabled: true
    username: ""
    password: ""
  homeassistant_api:
    token: ""                      # 일반적으로 비움: SUPERVISOR_TOKEN 자동 주입
    url: "http://supervisor/core"
    timeout: 30
  policy:
    default_location: "zone.home"  # 현재는 zone.home 우선, 실패 시 lat/lon 폴백
    lat: 36.123
    lon: 127.234
    radius_km_buffer: 10
    severity_threshold: "moderate" # minor|moderate|severe|critical
    night_mode: false
  tts:
    enabled: false
    topic: "dxsafety/tts"
    template: "{headline} - {description}"
  observability:
    http_port: 8099
    metrics_enabled: true
    log_level: "INFO"
  reliability:
    idempotency_ttl_sec: 86400
    reconnect_max_backoff_sec: 120
    max_retries: 5
    initial_delay: 1.0
    max_delay: 120.0
    backoff_factor: 2.0
    jitter: true
  shelter_nav:
    enabled: true
    file_path: "./share/shelter2025.xlsx"
    appname: "com.synctechno.dxsafety"
    notify_group: ""

schema:
  remote_mqtt:
    host: str
    port: port
    topic: str
    qos: int
    security_mode: list(none|tls|mtls)
    ca_cert_path: str?
    client_cert_path: str?
    client_key_path: str?
    username: str?
    password: password?
    keepalive: int
    clean_session: bool
    client_id: str?
  local_mqtt:
    host: str
    port: port
    topic_prefix: str
    qos: int
    retain: bool
    enabled: bool
    username: str?
    password: password?
  homeassistant_api:
    token: password?
    url: url
    timeout: int
  policy:
    default_location: str
    lat: float?
    lon: float?
    radius_km_buffer: float
    severity_threshold: list(minor|moderate|severe|critical)
    night_mode: bool
  tts:
    enabled: bool
    topic: str
    template: str
  observability:
    http_port: port
    metrics_enabled: bool
    log_level: str
  reliability:
    idempotency_ttl_sec: int
    reconnect_max_backoff_sec: int
    max_retries: int
    initial_delay: float
    max_delay: float
    backoff_factor: float
    jitter: bool
